### ISSUE TITLE
Kernel panic: GPF

### ISSUE THREAD

**Issue by CzrCraft** [synthels/eureka#4]
Kernel imedeatly panics when booting.
Might be my mistake not using a certain option in qemu, if so im sorry for posting this.
I also have a screenshot from qemu
![Screenshot from 2021-06-15 15-53-02](https://user-images.githubusercontent.com/52598300/122056070-eb189000-cdf1-11eb-9fe0-97da3f5fc380.png)

**Comment by synthels** [comment]
I am aware of this bug. The panic happens right when the kernel attempts to jump to ring 3. I have been trying to fix it for a while now... Will keep you updated

**Comment by CzrCraft** [comment]
> I am aware of this bug. The panic happens right when the kernel attempts to jump to ring 3. I have been trying to fix it for a while now... Will keep you updated

Thanks for letting me know!

**Comment by synthels** [comment]
This issue is now fixed!
